const princesses=[
 {id:'ariel',name:'アリエル',img:'assets/1000032634.webp'},
 {id:'rapunzel',name:'ラプンツェル',img:'assets/1000032637.webp'},
 {id:'jasmine',name:'ジャスミン',img:'assets/1000032644.webp'},
 {id:'snow',name:'しらゆきひめ',img:'assets/1000032645.webp'}
];
const levels={easy:{label:'やさしい',goal:3,slots:10,spawn:950,speed:[3.1,3.4],lanes:3,cardMax:190},normal:{label:'ふつう',goal:5,slots:14,spawn:600,speed:[2.3,2.55],lanes:3,cardMax:190},hard:{label:'むずかしい',goal:10,slots:25,tailSlots:4,spawn:400,speed:[2.0,2.2],lanes:4,cardMax:165}};
const $=s=>document.querySelector(s);let target=null,level=null,duration=10,score=0,time=10,playing=false,perfectShown=false,spawnQueue=[],laneStep=0,spawnTimer,tickTimer,feedbackTimer;
const show=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')};
princesses.forEach(p=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<img src="${p.img}" alt="${p.name}"><span>${p.name}</span>`;b.onclick=()=>choose(p);$('#choices').append(b)});
function choose(p){target=p;$('#difficultyImage').src=p.img;$('#difficultyImage').alt=p.name;$('#targetImage').src=p.img;$('#targetImage').alt=p.name;$('#targetName').textContent=p.name;$('#miniTarget').src=p.img;$('#miniName').textContent=p.name;show('difficulty')}
const goalCount=()=>level.goal*(duration/10);
const updateDifficultyLabels=()=>document.querySelectorAll('.difficulty-btn').forEach(b=>{const l=levels[b.dataset.level];b.querySelector('span').textContent=`${l.goal*(duration/10)}こで パーフェクト`});
document.querySelectorAll('.time-btn').forEach(b=>b.onclick=()=>{duration=Number(b.dataset.time);document.querySelectorAll('.time-btn').forEach(x=>x.classList.toggle('active',x===b));updateDifficultyLabels()});
document.querySelectorAll('.difficulty-btn').forEach(b=>b.onclick=()=>{level=levels[b.dataset.level];$('#goalText').textContent=`${duration}びょう・${level.label}：${goalCount()}こで パーフェクト！`;show('ready')});
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>{stop();show('select')});
$('#startBtn').onclick=start;$('#againBtn').onclick=start;
function start(){score=0;time=duration;playing=false;perfectShown=false;clearTimeout(feedbackTimer);$('#score').textContent=score;$('#time').textContent=time;$('#feedback').textContent='';$('#feedback').className='feedback';$('#resultBadge').textContent='';$('#resultBadge').className='result-badge';$('#perfectBurst').className='perfect-burst';$('#playfield').replaceChildren();show('game');let n=3;$('#countdown').textContent=n;const c=setInterval(()=>{n--;if(n>0)$('#countdown').textContent=n;else if(n===0)$('#countdown').textContent='GO!';else{clearInterval(c);$('#countdown').textContent='';begin()}},650)}
function begin(){playing=true;laneStep=Math.floor(Math.random()*level.lanes);spawnQueue=makeQueue();spawn();spawnTimer=setInterval(spawn,level.spawn);tickTimer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0)finish()},1000)}
function makeQueue(){const others=princesses.filter(p=>p.id!==target.id);const goal=goalCount();const slots=level.slots*(duration/10);const targetSpan=slots-(level.tailSlots||0);const queue=Array.from({length:slots},(_,i)=>others[i%others.length]);const used=new Set();for(let i=0;i<goal;i++){let pos=Math.floor((i+.5)*targetSpan/goal);while(used.has(pos)&&pos<targetSpan-1)pos++;used.add(pos);queue[pos]=target}return queue}
function spawn(){if(!playing)return;const others=princesses.filter(p=>p.id!==target.id);const p=spawnQueue.length?spawnQueue.shift():others[Math.floor(Math.random()*others.length)];const lane=laneStep%level.lanes;laneStep++;const field=$('#playfield');const laneWidth=field.clientWidth/level.lanes;const cardWidth=Math.min(laneWidth-10,level.cardMax);const img=document.createElement('img');img.className='falling';img.src=p.img;img.alt=p.name;img.dataset.id=p.id;img.style.width=`${cardWidth}px`;img.style.maxWidth='none';img.style.left=`${lane*laneWidth+(laneWidth-cardWidth)/2}px`;img.style.setProperty('--spin',`${Math.random()*8-4}deg`);img.style.animationDuration=`${level.speed[0]+Math.random()*(level.speed[1]-level.speed[0])}s`;img.onpointerdown=e=>hit(e,img,p);img.onanimationend=()=>img.remove();field.append(img)}
function hit(e,img,p){e.preventDefault();if(!playing||img.dataset.hit)return;img.dataset.hit='1';if(p.id===target.id){score++;$('#score').textContent=score;flash('せいかい！ ✨',true);if(score>=goalCount()&&!perfectShown){perfectShown=true;const burst=$('#perfectBurst');burst.classList.remove('show');void burst.offsetWidth;burst.classList.add('show')}img.style.transition='.25s';img.style.transform='scale(1.4)';img.style.opacity='0';setTimeout(()=>img.remove(),220)}else{flash('ちがうよ',false);img.animate([{transform:'translateX(-8px)'},{transform:'translateX(8px)'},{transform:'translateX(0)'}],{duration:220})}}
function flash(message,ok){const f=$('#feedback');clearTimeout(feedbackTimer);f.textContent=message;f.style.color=ok?'#ffe762':'#fff';f.classList.remove('pop');void f.offsetWidth;f.classList.add('pop');feedbackTimer=setTimeout(()=>{f.textContent='';f.classList.remove('pop')},480)}
function finish(){stop();$('#finalScore').textContent=score;$('#resultImage').src=target.img;$('#resultImage').alt=target.name;const badge=$('#resultBadge');const goal=goalCount();badge.textContent='';badge.className='result-badge';if(score>=goal)badge.classList.add('perfect');else badge.textContent=`あと ${goal-score}こで パーフェクト！`;setTimeout(()=>show('result'),250)}
function stop(){playing=false;clearInterval(spawnTimer);clearInterval(tickTimer)}
